# Generated by Django 5.2.1 on 2025-05-30 00:57

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='資源標題')),
                ('description', models.TextField(verbose_name='描述')),
                ('status', models.CharField(choices=[('pending_review', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending_review', max_length=20, verbose_name='狀態')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上傳日期')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='最後修改日期')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下載次數')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.category', verbose_name='分類')),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='resources.tag', verbose_name='標籤')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '資源',
                'verbose_name_plural': '資源',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resources.models.resource_attachment_path, verbose_name='文件')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件類型')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上傳日期')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='resources.resource', verbose_name='所屬資源')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['upload_date'],
            },
        ),
    ]
